"""add telemetry and remove round client

Revision ID: 5fa5d2df2b6d
Revises: fa40eaea617d
Create Date: 2026-04-21 18:55:37.137431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fa5d2df2b6d'
down_revision: Union[str, Sequence[str], None] = 'fa40eaea617d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('acc_long', sa.Float(), nullable=True),
    sa.Column('acc_lat', sa.Float(), nullable=True),
    sa.Column('engine_speed', sa.Float(), nullable=True),
    sa.Column('throttle_position', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_telemetry_client_time', 'telemetry', ['client_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_telemetry_session', 'telemetry', ['session_id'], unique=False)
    op.drop_table('round_client_aggregates')
    op.alter_column('client_submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('clients', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.add_column('federation_rounds', sa.Column('aggregation_type', sa.String(length=50), nullable=True))
    op.alter_column('federation_rounds', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('federation_rounds', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('federation_rounds', 'finished_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('global_model_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_model_versions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('federation_rounds', 'finished_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('federation_rounds', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('federation_rounds', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('federation_rounds', 'aggregation_type')
    op.alter_column('clients', 'registered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('client_submissions', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('round_client_aggregates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('round_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('c', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('p', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('s', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('q', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('cluster_aggressive', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('cluster_normal', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('cluster_calm', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=False),
    sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mean_percentage_error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('round_client_aggregates_client_id_fkey')),
    sa.ForeignKeyConstraint(['round_id'], ['federation_rounds.id'], name=op.f('round_client_aggregates_round_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('round_client_aggregates_pkey'))
    )
    op.drop_index('ix_telemetry_session', table_name='telemetry')
    op.drop_index('ix_telemetry_client_time', table_name='telemetry')
    op.drop_table('telemetry')
    # ### end Alembic commands ###
