"""first version

Revision ID: fa40eaea617d
Revises: 
Create Date: 2026-04-19 20:19:20.095417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa40eaea617d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_submissions', sa.Column('num_samples', sa.Integer(), nullable=True))
    op.add_column('client_submissions', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('client_submissions', sa.Column('mean_percentage_error', sa.Float(), nullable=True))
    op.add_column('global_model_versions', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('global_model_versions', sa.Column('mean_percentage_error', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'global_model_versions', 'federation_rounds', ['round_id'], ['id'])
    op.add_column('round_client_aggregates', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('round_client_aggregates', sa.Column('mean_percentage_error', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'round_client_aggregates', 'federation_rounds', ['round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'round_client_aggregates', type_='foreignkey')
    op.drop_column('round_client_aggregates', 'mean_percentage_error')
    op.drop_column('round_client_aggregates', 'accuracy')
    op.drop_constraint(None, 'global_model_versions', type_='foreignkey')
    op.drop_column('global_model_versions', 'mean_percentage_error')
    op.drop_column('global_model_versions', 'accuracy')
    op.drop_column('client_submissions', 'mean_percentage_error')
    op.drop_column('client_submissions', 'accuracy')
    op.drop_column('client_submissions', 'num_samples')
    # ### end Alembic commands ###
